INSERT INTO `stock` VALUES ('1000', '25x200 mm. trykimp. Brædt', 3600, 1, 'stk', 17983);
INSERT INTO `stock` VALUES ('1001', '25x200 mm. trykimp. Brædt', 5400, 1, 'stk', 26973);
INSERT INTO `stock` VALUES ('1002', '25x125mm. trykimp. Brædt', 3600, 1, 'stk', 10783);
INSERT INTO `stock` VALUES ('1003', '25x125mm. trykimp. Brædt', 5400, 1, 'stk', 16173);
INSERT INTO `stock` VALUES ('1004', '38x73 mm. Lægte ubh.', 4200, 1, 'stk', 2499);
INSERT INTO `stock` VALUES ('1005', '45x95 mm. Reglar ub.', 2400, 1, 'stk', 3108);
INSERT INTO `stock` VALUES ('1006', '45x95 mm. Reglar ub.', 2700, 1, 'stk', 3496);
INSERT INTO `stock` VALUES ('1007', '45x195 mm. spærtræ ubh.', 4800, 1, 'stk', 23016);
INSERT INTO `stock` VALUES ('1008', '45x195 mm. spærtræ ubh.', 6000, 1, 'stk', 28770);
INSERT INTO `stock` VALUES ('1009', '97x97 mm. trykimp. Stolpe', 3000, 1, 'stk', 11385);
INSERT INTO `stock` VALUES ('1010', '19x100 mm. trykimp. Brædt', 2100, 1, 'stk', 1250);
INSERT INTO `stock` VALUES ('1011', '19x100 mm. trykimp. Brædt', 3600, 1, 'stk', 2143);
INSERT INTO `stock` VALUES ('1012', '19x100 mm. trykimp. Brædt', 5400, 1, 'stk', 3213);
INSERT INTO `stock` VALUES ('1013', 'Plastmo Ecolite blåtonet', 3600, 1, 'stk', 11900);
INSERT INTO `stock` VALUES ('1014', 'Plastmo Ecolite blåtonet', 6000, 1, 'stk', 23000);
INSERT INTO `stock` VALUES ('1015', '38x73 mm. taglægte T1', 5400, 1, 'stk', 9153);
INSERT INTO `stock` VALUES ('1016', '38x73 mm. taglægte T1', 4200, 1, 'stk', 7119);
INSERT INTO `stock` VALUES ('1030', 'Plastmo bundskruer 200 stk.', 0, 200, 'pakke', 39500);
INSERT INTO `stock` VALUES ('1031', 'Hulbånd 1x20 mm. 10 mtr.', 1000, 1, 'rulle', 20900);
INSERT INTO `stock` VALUES ('1032-r', 'Universal 190 mm højre', 190, 1, 'stk', 1590);
INSERT INTO `stock` VALUES ('1032-l', 'Universal 190 mm venstre', 190, 1, 'stk', 1590);
INSERT INTO `stock` VALUES ('1034', '4,5x60 mm. skruer 200 stk.', 60, 200, 'pakke', 15900);
INSERT INTO `stock` VALUES ('1035', '4,0x50 mm. skruer 250 stk.', 50, 250, 'pakke', 22900);
INSERT INTO `stock` VALUES ('1036', 'Bræddebolt 10x120 mm.', 120, 1, 'stk', 27900);
INSERT INTO `stock` VALUES ('1037', 'Firkantskiver 40x40x11mm', 11, 1, 'stk', 28900);
INSERT INTO `stock` VALUES ('1038', '4,5x70 mm. Skruer 400 stk.', 70, 400, 'pakke', 19900);
INSERT INTO `stock` VALUES ('1039', '4,5x50 mm. Skruer 300 stk.', 50, 300, 'pakke', 9595);
INSERT INTO `stock` VALUES ('1040', 'Stalddørsgreb 50x75 mm', 75, 1, 'sæt', 14320);
INSERT INTO `stock` VALUES ('1041', 'T hængsel 390 mm', 390, 1, 'stk', 6396);
INSERT INTO `stock` VALUES ('1042', 'Vinkelbeslag 35 mm', 35, 1, 'stk', 2495);
INSERT INTO `stock` VALUES ('1043', '5,0 x 40 mm. beslagskruer 250 stk.', 40, 250, 'pakke', 21000);
INSERT INTO `stock` VALUES ('1044', '5,0 x 100 mm. skruer 100 stk', 100, 100, 'pakke', 18900);
INSERT INTO `stock` VALUES ('1060', 'B & C Dobbelt -s sort', 0, 300, 'stk', 589);
INSERT INTO `stock` VALUES ('1061', 'B & C Rygsten sort', 0, 1, 'stk', 4500);
INSERT INTO `stock` VALUES ('1062', 'B & C Toplægte holder', 0, 1, 'stk', 1995);
INSERT INTO `stock` VALUES ('1063', 'B & C Rygstensbeslag', 0, 1, 'stk', 1010);
INSERT INTO `stock` VALUES ('1064', 'B & C Tagstens bindere & nakkekroge', 0, 1, 'pakke', 81900);
INSERT INTO `categories`(name) VALUES ('Understernbrædder');
INSERT INTO `categories`(name) VALUES ('Oversternbrædder');
INSERT INTO `categories`(name) VALUES ('Lægter');
INSERT INTO `categories`(name) VALUES ('Reglar');
INSERT INTO `categories`(name) VALUES ('Spærtræ');
INSERT INTO `categories`(name) VALUES ('Rem');
INSERT INTO `categories`(name) VALUES ('Stolpe');
INSERT INTO `categories`(name) VALUES ('Brædt');
INSERT INTO `categories`(name) VALUES ('Vandbræt');
INSERT INTO `categories`(name) VALUES ('Tagplader');
INSERT INTO `categories`(name) VALUES ('Skruer');
INSERT INTO `categories`(name) VALUES ('Hulbånd');
INSERT INTO `categories`(name) VALUES ('Beslag');
INSERT INTO `categories`(name) VALUES ('Bolt');
INSERT INTO `categories`(name) VALUES ('Skiver');
INSERT INTO `categories`(name) VALUES ('ShedMisc');
INSERT INTO `categories`(name) VALUES ('Tagpakke');
INSERT INTO `stockToCategory` VALUES ('1000',1);
INSERT INTO `stockToCategory` VALUES ('1001',1);
INSERT INTO `stockToCategory` VALUES ('1002',2);
INSERT INTO `stockToCategory` VALUES ('1003',2);
INSERT INTO `stockToCategory` VALUES ('1004',3);
INSERT INTO `stockToCategory` VALUES ('1005',4);
INSERT INTO `stockToCategory` VALUES ('1006',4);
INSERT INTO `stockToCategory` VALUES ('1007',5);
INSERT INTO `stockToCategory` VALUES ('1008',5);
INSERT INTO `stockToCategory` VALUES ('1007',6);
INSERT INTO `stockToCategory` VALUES ('1008',6);
INSERT INTO `stockToCategory` VALUES ('1009',7);
INSERT INTO `stockToCategory` VALUES ('1010',8);
INSERT INTO `stockToCategory` VALUES ('1011',8);
INSERT INTO `stockToCategory` VALUES ('1012',8);
INSERT INTO `stockToCategory` VALUES ('1010',9);
INSERT INTO `stockToCategory` VALUES ('1011',9);
INSERT INTO `stockToCategory` VALUES ('1012',9);
INSERT INTO `stockToCategory` VALUES ('1013',10);
INSERT INTO `stockToCategory` VALUES ('1014',10);
INSERT INTO `stockToCategory` VALUES ('1015',3);
INSERT INTO `stockToCategory` VALUES ('1016',3);
INSERT INTO `stockToCategory` VALUES ('1030',11);
INSERT INTO `stockToCategory` VALUES ('1034',11);
INSERT INTO `stockToCategory` VALUES ('1035',11);
INSERT INTO `stockToCategory` VALUES ('1038',11);
INSERT INTO `stockToCategory` VALUES ('1039',11);
INSERT INTO `stockToCategory` VALUES ('1031',12);
INSERT INTO `stockToCategory` VALUES ('1032-r',13);
INSERT INTO `stockToCategory` VALUES ('1032-l',13);
INSERT INTO `stockToCategory` VALUES ('1042',13);
INSERT INTO `stockToCategory` VALUES ('1036',14);
INSERT INTO `stockToCategory` VALUES ('1037',15);
INSERT INTO `stockToCategory` VALUES ('1040',16);
INSERT INTO `stockToCategory` VALUES ('1041',16);
INSERT INTO `stockToCategory` VALUES ('1004',16);
INSERT INTO `stockToCategory` VALUES ('1043',11);
INSERT INTO `stockToCategory` VALUES ('1044',11);
INSERT INTO `stockToCategory` VALUES ('1060',17);
INSERT INTO `stockToCategory` VALUES ('1061',17);
INSERT INTO `stockToCategory` VALUES ('1062',17);
INSERT INTO `stockToCategory` VALUES ('1063',17);
INSERT INTO `stockToCategory` VALUES ('1064',17);
INSERT INTO `users` VALUES ('Cecil', 'Cecil@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Mariano', 'Mariano@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Damien', 'Damien@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Arlen', 'Arlen@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Philip', 'Philip@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Johnny', 'Johnny@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Adrian', 'Adrian@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Matt', 'Matt@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Svetlana', 'Svetlana@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Andy', 'Andy@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Lovie', 'Lovie@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Irvin', 'Irvin@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Floyd', 'Floyd@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Kristi', 'Kristi@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Dani', 'Dani@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Sharyn', 'Sharyn@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Xochitl', 'Xochitl@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Kim', 'Kim@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Armand', 'Armand@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Wally', 'Wally@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Eldridge', 'Eldridge@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Aaron', 'Aaron@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Sonny', 'Sonny@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Kristian', 'Kristian@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Harriett', 'Harriett@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Kasey', 'Kasey@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Era', 'Era@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Sherlene', 'Sherlene@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Weston', 'Weston@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Joel', 'Joel@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Candy', 'Candy@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Brandon', 'Brandon@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Jewell', 'Jewell@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Bell', 'Bell@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Daina', 'Daina@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Heather', 'Heather@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Rodney', 'Rodney@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Brady', 'Brady@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Louetta', 'Louetta@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Tatum', 'Tatum@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Faustino', 'Faustino@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Kelley', 'Kelley@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Darren', 'Darren@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Freddy', 'Freddy@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Dong', 'Dong@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Lissa', 'Lissa@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Reuben', 'Reuben@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Danny', 'Danny@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Marcelino', 'Marcelino@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Roland', 'Roland@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Nora', 'Nora@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Johnette', 'Johnette@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Elton', 'Elton@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Harris', 'Harris@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Jude', 'Jude@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Lucile', 'Lucile@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Perry', 'Perry@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Daria', 'Daria@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Jospeh', 'Jospeh@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Oliver', 'Oliver@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Bret', 'Bret@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Bethanie', 'Bethanie@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Joi', 'Joi@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Mechelle', 'Mechelle@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Estefana', 'Estefana@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Michaela', 'Michaela@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Salley', 'Salley@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Marquerite', 'Marquerite@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Tiana', 'Tiana@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Booker', 'Booker@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Divina', 'Divina@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Dalila', 'Dalila@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Deirdre', 'Deirdre@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Rosette', 'Rosette@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Rudy', 'Rudy@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Laila', 'Laila@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Chelsea', 'Chelsea@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Alejandro', 'Alejandro@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Jonathan', 'Jonathan@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Ashanti', 'Ashanti@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Marshall', 'Marshall@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Yaeko', 'Yaeko@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Ressie', 'Ressie@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Denver', 'Denver@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Jonas', 'Jonas@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Hiedi', 'Hiedi@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Lynsey', 'Lynsey@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Shayne', 'Shayne@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Todd', 'Todd@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Randy', 'Randy@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Idalia', 'Idalia@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Jefferey', 'Jefferey@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Darrin', 'Darrin@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Willard', 'Willard@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('German', 'German@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Annette', 'Annette@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Violet', 'Violet@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Arron', 'Arron@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Adan', 'Adan@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('Kathaleen', 'Kathaleen@somewhere.dk', '1234', 'CUSTOMER');
INSERT INTO `users` VALUES ('BestSalesman', 'BestSalesman@somewhere.dk', '1234', 'EMPLOYEE');
INSERT INTO `users` VALUES ('Admin', 'Admin@somewhere.dk', '1234', 'ADMIN');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (571, 571, 158, 158, 'not flat', 30, 'Jodee', '521 McClure Point', 'Jodees Zip', '642.978.6702', 'Jodee@somewhere.com', 'This is a test for Jodee');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (540, 540, 131, 131, 'not flat', 30, 'Magdalen', '29770 Sharleen Vista', 'Magdalens Zip', '1-925-206-8653', 'Magdalen@somewhere.com', 'This is a test for Magdalen');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (533, 533, 118, 118, 'not flat', 30, 'Garret', '0248 Cartwright Villages', 'Garrets Zip', '698.671.9000', 'Garret@somewhere.com', 'This is a test for Garret');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (736, 736, 117, 117, 'not flat', 30, 'Lyndon', '197 Felix Fields', 'Lyndons Zip', '735-250-8845', 'Lyndon@somewhere.com', 'This is a test for Lyndon');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (693, 693, 115, 115, 'not flat', 30, 'Antony', '783 Sandy Common', 'Antonys Zip', '(549) 804-7225', 'Antony@somewhere.com', 'This is a test for Antony');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (666, 666, 149, 149, 'not flat', 30, 'Truman', '1413 Elias Crossroad', 'Trumans Zip', '(085) 987-7496', 'Truman@somewhere.com', 'This is a test for Truman');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (639, 639, 163, 163, 'not flat', 30, 'Edison', '52333 Jeremiah Row', 'Edisons Zip', '1-537-110-6248', 'Edison@somewhere.com', 'This is a test for Edison');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (603, 603, 131, 131, 'not flat', 30, 'Manual', '27097 Chance Islands', 'Manuals Zip', '(800) 941-8314', 'Manual@somewhere.com', 'This is a test for Manual');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (753, 753, 171, 171, 'not flat', 30, 'Williams', '80022 Morissette Views', 'Williamss Zip', '709-482-1820', 'Williams@somewhere.com', 'This is a test for Williams');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (583, 583, 117, 117, 'not flat', 30, 'Sherwood', '22045 Bridgett Wells', 'Sherwoods Zip', '493.805.2646', 'Sherwood@somewhere.com', 'This is a test for Sherwood');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (712, 712, 161, 161, 'not flat', 30, 'Abraham', '56753 Lemke Key', 'Abrahams Zip', '(430) 200-9453', 'Abraham@somewhere.com', 'This is a test for Abraham');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (623, 623, 146, 146, 'not flat', 30, 'Helene', '1209 Walter Crescent', 'Helenes Zip', '(789) 765-1276', 'Helene@somewhere.com', 'This is a test for Helene');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (509, 509, 111, 111, 'not flat', 30, 'Kelsie', '45812 Josh Court', 'Kelsies Zip', '1-981-445-4121', 'Kelsie@somewhere.com', 'This is a test for Kelsie');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (746, 746, 201, 201, 'not flat', 30, 'Jon', '2272 Hahn Oval', 'Jons Zip', '027-930-9404', 'Jon@somewhere.com', 'This is a test for Jon');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (701, 701, 154, 154, 'not flat', 30, 'Clayton', '2289 Galen Road', 'Claytons Zip', '503.997.5134', 'Clayton@somewhere.com', 'This is a test for Clayton');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (704, 704, 122, 122, 'not flat', 30, 'Riley', '594 Spencer Island', 'Rileys Zip', '951-894-8002', 'Riley@somewhere.com', 'This is a test for Riley');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (632, 632, 151, 151, 'not flat', 30, 'Kareem', '65427 Roberts Hill', 'Kareems Zip', '1-664-115-6208', 'Kareem@somewhere.com', 'This is a test for Kareem');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (673, 673, 162, 162, 'not flat', 30, 'Shanelle', '439 Neville Island', 'Shanelles Zip', '1-899-154-5612', 'Shanelle@somewhere.com', 'This is a test for Shanelle');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (757, 757, 154, 154, 'not flat', 30, 'Shirly', '432 Carrol Radial', 'Shirlys Zip', '872-674-7807', 'Shirly@somewhere.com', 'This is a test for Shirly');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (522, 522, 190, 190, 'not flat', 30, 'Oscar', '888 Deckow Shore', 'Oscars Zip', '(164) 128-7098', 'Oscar@somewhere.com', 'This is a test for Oscar');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (624, 624, 204, 204, 'not flat', 30, 'Maurine', '742 Enrique Square', 'Maurines Zip', '1-908-781-8576', 'Maurine@somewhere.com', 'This is a test for Maurine');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (590, 590, 126, 126, 'not flat', 30, 'Linh', '619 Strosin Burg', 'Linhs Zip', '233-361-2327', 'Linh@somewhere.com', 'This is a test for Linh');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (712, 712, 118, 118, 'not flat', 30, 'Delphine', '1524 Isabel Roads', 'Delphines Zip', '1-317-764-3701', 'Delphine@somewhere.com', 'This is a test for Delphine');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (502, 502, 171, 171, 'not flat', 30, 'Queenie', '1639 Gisela Tunnel', 'Queenies Zip', '(110) 805-2140', 'Queenie@somewhere.com', 'This is a test for Queenie');
INSERT INTO `requests`(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (508, 508, 102, 102, 'not flat', 30, 'Theressa', '8514 Amada Spur', 'Theressas Zip', '(395) 182-7329', 'Theressa@somewhere.com', 'This is a test for Theressa');
