-- Woods
INSERT INTO stock VALUES ('1000', '25x200 mm. trykimp. Brædt', 3600, 1, 'stk', 17983);
INSERT INTO stock VALUES ('1001', '25x200 mm. trykimp. Brædt', 5400, 1, 'stk', 26973);
INSERT INTO stock VALUES ('1002', '25x125mm. trykimp. Brædt', 3600, 1, 'stk', 10783);
INSERT INTO stock VALUES ('1003', '25x125mm. trykimp. Brædt', 5400, 1, 'stk', 16173);
INSERT INTO stock VALUES ('1004', '38x73 mm. Lægte ubh.', 4200, 1, 'stk', 2499);
INSERT INTO stock VALUES ('1005', '45x95 mm. Reglar ub.', 2400, 1, 'stk', 3108);
INSERT INTO stock VALUES ('1006', '45x95 mm. Reglar ub.', 2700, 1, 'stk', 3496);
INSERT INTO stock VALUES ('1007', '45x195 mm. spærtræ ubh.', 4800, 1, 'stk', 23016);
INSERT INTO stock VALUES ('1008', '45x195 mm. spærtræ ubh.', 6000, 1, 'stk', 28770);
INSERT INTO stock VALUES ('1009', '97x97 mm. trykimp. Stolpe', 3000, 1, 'stk', 11385);
INSERT INTO stock VALUES ('1010', '19x100 mm. trykimp. Brædt', 2100, 1, 'stk', 1250);
INSERT INTO stock VALUES ('1011', '19x100 mm. trykimp. Brædt', 3600, 1, 'stk', 2143);
INSERT INTO stock VALUES ('1012', '19x100 mm. trykimp. Brædt', 5400, 1, 'stk', 3213);
INSERT INTO stock VALUES ('1013', 'Plastmo Ecolite blåtonet', 3600, 1, 'stk', 11900);
INSERT INTO stock VALUES ('1014', 'Plastmo Ecolite blåtonet', 6000, 1, 'stk', 23000);
INSERT INTO stock VALUES ('1015', '38x73 mm. taglægte T1', 5400, 1, 'stk', 9153);
INSERT INTO stock VALUES ('1016', '38x73 mm. taglægte T1', 4200, 1, 'stk', 7119);
INSERT INTO stock VALUES ('1030', 'Plastmo bundskruer 200 stk.', 0, 200, 'pakke', 39500);
INSERT INTO stock VALUES ('1031', 'Hulbånd 1x20 mm. 10 mtr.', 1000, 1, 'rulle', 20900);
INSERT INTO stock VALUES ('1032-r', 'Universal 190 mm højre', 190, 1, 'stk', 1590);
INSERT INTO stock VALUES ('1032-l', 'Universal 190 mm venstre', 190, 1, 'stk', 1590);
INSERT INTO stock VALUES ('1034', '4,5x60 mm. skruer 200 stk.', 60, 200, 'pakke', 15900);
INSERT INTO stock VALUES ('1035', '4,0x50 mm. skruer 250 stk.', 50, 250, 'pakke', 22900);
INSERT INTO stock VALUES ('1036', 'Bræddebolt 10x120 mm.', 120, 1, 'stk', 27900);
INSERT INTO stock VALUES ('1037', 'Firkantskiver 40x40x11mm', 11, 1, 'stk', 28900);
INSERT INTO stock VALUES ('1038', '4,5x70 mm. Skruer 400 stk.', 70, 400, 'pakke', 19900);
INSERT INTO stock VALUES ('1039', '4,5x50 mm. Skruer 300 stk.', 50, 300, 'pakke', 9595);
INSERT INTO stock VALUES ('1040', 'Stalddørsgreb 50x75 mm', 75, 1, 'sæt', 14320);
INSERT INTO stock VALUES ('1041', 'T hængsel 390 mm', 390, 1, 'stk', 6396);
INSERT INTO stock VALUES ('1042', 'Vinkelbeslag 35 mm', 35, 1, 'stk', 2495);
INSERT INTO stock VALUES ('1043', '5,0 x 40 mm. beslagskruer 250 stk.', 40, 250, 'pakke', 21000);
INSERT INTO stock VALUES ('1044', '5,0 x 100 mm. skruer 100 stk', 100, 100, 'pakke', 18900);
INSERT INTO stock VALUES ('1060', 'B & C Dobbelt -s sort', 0, 300, 'stk', 589);
INSERT INTO stock VALUES ('1061', 'B & C Rygsten sort', 0, 1, 'stk', 4500);
INSERT INTO stock VALUES ('1062', 'B & C Toplægte holder', 0, 1, 'stk', 1995);
INSERT INTO stock VALUES ('1063', 'B & C Rygstensbeslag', 0, 1, 'stk', 1010);
INSERT INTO stock VALUES ('1064', 'B & C Tagstens bindere & nakkekroge', 0, 1, 'pakke', 81900);


-- Categories
INSERT INTO categories(name) VALUES ('Understernbrædder');
INSERT INTO categories(name) VALUES ('Oversternbrædder');
INSERT INTO categories(name) VALUES ('Lægter');
INSERT INTO categories(name) VALUES ('Reglar');
INSERT INTO categories(name) VALUES ('Spærtræ');
INSERT INTO categories(name) VALUES ('Rem');
INSERT INTO categories(name) VALUES ('Stolpe');
INSERT INTO categories(name) VALUES ('Brædt');
INSERT INTO categories(name) VALUES ('Vandbræt');
INSERT INTO categories(name) VALUES ('Tagplader');
INSERT INTO categories(name) VALUES ('Skruer');
INSERT INTO categories(name) VALUES ('Hulbånd');
INSERT INTO categories(name) VALUES ('Beslag');
INSERT INTO categories(name) VALUES ('Bolt');
INSERT INTO categories(name) VALUES ('Skiver');
INSERT INTO categories(name) VALUES ('ShedMisc');
INSERT INTO categories(name) VALUES ('Tagpakke');


-- Categories - Stock link
INSERT INTO stockToCategory VALUES ('1000',1);
INSERT INTO stockToCategory VALUES ('1001',1);
INSERT INTO stockToCategory VALUES ('1002',2);
INSERT INTO stockToCategory VALUES ('1003',2);
INSERT INTO stockToCategory VALUES ('1004',3);
INSERT INTO stockToCategory VALUES ('1005',4);
INSERT INTO stockToCategory VALUES ('1006',4);
INSERT INTO stockToCategory VALUES ('1007',5);
INSERT INTO stockToCategory VALUES ('1008',5);
INSERT INTO stockToCategory VALUES ('1007',6);
INSERT INTO stockToCategory VALUES ('1008',6);
INSERT INTO stockToCategory VALUES ('1009',7);
INSERT INTO stockToCategory VALUES ('1010',8);
INSERT INTO stockToCategory VALUES ('1011',8);
INSERT INTO stockToCategory VALUES ('1012',8);
INSERT INTO stockToCategory VALUES ('1010',9);
INSERT INTO stockToCategory VALUES ('1011',9);
INSERT INTO stockToCategory VALUES ('1012',9);
INSERT INTO stockToCategory VALUES ('1013',10);
INSERT INTO stockToCategory VALUES ('1014',10);
INSERT INTO stockToCategory VALUES ('1015',3);
INSERT INTO stockToCategory VALUES ('1016',3);
INSERT INTO stockToCategory VALUES ('1030',11);
INSERT INTO stockToCategory VALUES ('1034',11);
INSERT INTO stockToCategory VALUES ('1035',11);
INSERT INTO stockToCategory VALUES ('1038',11);
INSERT INTO stockToCategory VALUES ('1039',11);
INSERT INTO stockToCategory VALUES ('1031',12);
INSERT INTO stockToCategory VALUES ('1032-r',13);
INSERT INTO stockToCategory VALUES ('1032-l',13);
INSERT INTO stockToCategory VALUES ('1042',13);
INSERT INTO stockToCategory VALUES ('1036',14);
INSERT INTO stockToCategory VALUES ('1037',15);
INSERT INTO stockToCategory VALUES ('1040',16);
INSERT INTO stockToCategory VALUES ('1041',16);
INSERT INTO stockToCategory VALUES ('1004',16);
INSERT INTO stockToCategory VALUES ('1043',11);
INSERT INTO stockToCategory VALUES ('1044',11);
INSERT INTO stockToCategory VALUES ('1060',17);
INSERT INTO stockToCategory VALUES ('1061',17);
INSERT INTO stockToCategory VALUES ('1062',17);
INSERT INTO stockToCategory VALUES ('1063',17);
INSERT INTO stockToCategory VALUES ('1064',17);


-- Users
INSERT INTO users VALUES ('Granville', 'Granville@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Jim', 'Jim@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Odis', 'Odis@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Winfred', 'Winfred@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Rodger', 'Rodger@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Arleen', 'Arleen@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Jared', 'Jared@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Christian', 'Christian@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Tomas', 'Tomas@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Arnoldo', 'Arnoldo@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Danial', 'Danial@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Rosendo', 'Rosendo@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Katelynn', 'Katelynn@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Edison', 'Edison@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Isadora', 'Isadora@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Weston', 'Weston@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Sanjuanita', 'Sanjuanita@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Jeramy', 'Jeramy@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Carey', 'Carey@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Ned', 'Ned@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Benjamin', 'Benjamin@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Frederick', 'Frederick@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Jeanelle', 'Jeanelle@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Bok', 'Bok@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Evangelina', 'Evangelina@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Krystin', 'Krystin@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Angelo', 'Angelo@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Simon', 'Simon@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Eldon', 'Eldon@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Judi', 'Judi@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Sandee', 'Sandee@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Seth', 'Seth@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Danny', 'Danny@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Lashunda', 'Lashunda@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Audrea', 'Audrea@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Joane', 'Joane@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Ammie', 'Ammie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Goldie', 'Goldie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Bobette', 'Bobette@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Treasa', 'Treasa@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Queenie', 'Queenie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Sam', 'Sam@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Terence', 'Terence@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Tyron', 'Tyron@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Henry', 'Henry@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Brain', 'Brain@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Porfirio', 'Porfirio@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Jewell', 'Jewell@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Willodean', 'Willodean@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Brice', 'Brice@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Waltraud', 'Waltraud@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Jonna', 'Jonna@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Benito', 'Benito@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Stanford', 'Stanford@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Donnell', 'Donnell@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Dalton', 'Dalton@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Ezequiel', 'Ezequiel@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Marilu', 'Marilu@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Denise', 'Denise@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Brittany', 'Brittany@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Debrah', 'Debrah@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Laurie', 'Laurie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Ouida', 'Ouida@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Joe', 'Joe@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Reed', 'Reed@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Robin', 'Robin@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Wynell', 'Wynell@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Malisa', 'Malisa@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Marcelino', 'Marcelino@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Gabriele', 'Gabriele@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Casandra', 'Casandra@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Elton', 'Elton@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Marylee', 'Marylee@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Bari', 'Bari@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Jimmy', 'Jimmy@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Latashia', 'Latashia@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Josephine', 'Josephine@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Stacia', 'Stacia@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Garfield', 'Garfield@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Chung', 'Chung@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Alva', 'Alva@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Lara', 'Lara@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Seymour', 'Seymour@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Adriana', 'Adriana@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Corrie', 'Corrie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Johnny', 'Johnny@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Lonnie', 'Lonnie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Marna', 'Marna@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Nathanial', 'Nathanial@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Ali', 'Ali@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Jamie', 'Jamie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Wyatt', 'Wyatt@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Elliott', 'Elliott@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Cathie', 'Cathie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Michelina', 'Michelina@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Denny', 'Denny@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Bradford', 'Bradford@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Francisco', 'Francisco@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Annabel', 'Annabel@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Clifford', 'Clifford@somewhere.dk', '1234', 'SALESMAN');


-- Requests
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (723, 723, 181, 181, 'not flat', 30, 'Latonya', '2648 Anderson Meadows', 'Latonyas Zip', '1-041-625-4088', 'Latonya@somewhere.com', 'This is a test for Latonya');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (692, 692, 158, 158, 'not flat', 30, 'Mercedez', '8717 Emery Summit', 'Mercedezs Zip', '(809) 057-4443', 'Mercedez@somewhere.com', 'This is a test for Mercedez');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (654, 654, 200, 200, 'not flat', 30, 'Jacklyn', '57732 Klein Parks', 'Jacklyns Zip', '245.187.1352', 'Jacklyn@somewhere.com', 'This is a test for Jacklyn');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (668, 668, 111, 111, 'not flat', 30, 'Melia', '01253 Gabriel Course', 'Melias Zip', '802.007.5389', 'Melia@somewhere.com', 'This is a test for Melia');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (517, 517, 165, 165, 'not flat', 30, 'Everett', '519 Dickens Springs', 'Everetts Zip', '(957) 323-7277', 'Everett@somewhere.com', 'This is a test for Everett');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (510, 510, 139, 139, 'not flat', 30, 'Chong', '741 Boyle Branch', 'Chongs Zip', '1-835-781-7263', 'Chong@somewhere.com', 'This is a test for Chong');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (753, 753, 199, 199, 'not flat', 30, 'Leonore', '53377 Carisa Garden', 'Leonores Zip', '134-611-5496', 'Leonore@somewhere.com', 'This is a test for Leonore');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (749, 749, 102, 102, 'not flat', 30, 'Elton', '588 Kub Extension', 'Eltons Zip', '704.060.4710', 'Elton@somewhere.com', 'This is a test for Elton');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (511, 511, 106, 106, 'not flat', 30, 'Devin', '746 Man Common', 'Devins Zip', '387.279.6576', 'Devin@somewhere.com', 'This is a test for Devin');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (509, 509, 135, 135, 'not flat', 30, 'Georgina', '7083 Rosenbaum Shore', 'Georginas Zip', '217.849.6328', 'Georgina@somewhere.com', 'This is a test for Georgina');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (524, 524, 147, 147, 'not flat', 30, 'Oliver', '74153 Jamey Crescent', 'Olivers Zip', '062.823.7124', 'Oliver@somewhere.com', 'This is a test for Oliver');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (722, 722, 188, 188, 'not flat', 30, 'Nicholas', '9450 Keely Garden', 'Nicholass Zip', '(114) 637-3013', 'Nicholas@somewhere.com', 'This is a test for Nicholas');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (571, 571, 165, 165, 'not flat', 30, 'Lavon', '28230 Jenkins Ramp', 'Lavons Zip', '(029) 685-5911', 'Lavon@somewhere.com', 'This is a test for Lavon');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (755, 755, 161, 161, 'not flat', 30, 'Darin', '2192 Kub Spring', 'Darins Zip', '933.249.1254', 'Darin@somewhere.com', 'This is a test for Darin');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (748, 748, 123, 123, 'not flat', 30, 'Valentin', '119 Glover Ranch', 'Valentins Zip', '1-513-127-3361', 'Valentin@somewhere.com', 'This is a test for Valentin');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (729, 729, 126, 126, 'not flat', 30, 'Vito', '031 Hilaria Mountain', 'Vitos Zip', '007-946-2216', 'Vito@somewhere.com', 'This is a test for Vito');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (733, 733, 183, 183, 'not flat', 30, 'Cyrus', '119 Mindi Crossing', 'Cyruss Zip', '856.010.7296', 'Cyrus@somewhere.com', 'This is a test for Cyrus');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (752, 752, 123, 123, 'not flat', 30, 'Olen', '490 Spinka Turnpike', 'Olens Zip', '492.242.6507', 'Olen@somewhere.com', 'This is a test for Olen');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (718, 718, 204, 204, 'not flat', 30, 'Manuel', '829 King Lodge', 'Manuels Zip', '1-630-456-0022', 'Manuel@somewhere.com', 'This is a test for Manuel');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (706, 706, 189, 189, 'not flat', 30, 'Devona', '360 Zemlak Mount', 'Devonas Zip', '516-673-4039', 'Devona@somewhere.com', 'This is a test for Devona');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (603, 603, 129, 129, 'not flat', 30, 'Cleora', '6085 Lorrie Street', 'Cleoras Zip', '285.907.7891', 'Cleora@somewhere.com', 'This is a test for Cleora');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (587, 587, 140, 140, 'not flat', 30, 'Floyd', '837 Braun Plains', 'Floyds Zip', '1-822-885-5021', 'Floyd@somewhere.com', 'This is a test for Floyd');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (544, 544, 159, 159, 'not flat', 30, 'Burton', '264 Beatrice Fords', 'Burtons Zip', '473.552.4322', 'Burton@somewhere.com', 'This is a test for Burton');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (744, 744, 167, 167, 'not flat', 30, 'Sheron', '21131 Lakin Villages', 'Sherons Zip', '649.579.3334', 'Sheron@somewhere.com', 'This is a test for Sheron');
INSERT INTO requests(width, length, shedWidth, shedLength, roof, angle, name, address, zipCity, phone, email, note) VALUES (646, 646, 123, 123, 'not flat', 30, 'Jarod', '046 Lemke River', 'Jarods Zip', '(826) 308-8576', 'Jarod@somewhere.com', 'This is a test for Jarod');
