-- Woods
INSERT INTO stock VALUES ('1000', '25x200 mm. trykimp. Brædt', 360, 1, 'stk');
INSERT INTO stock VALUES ('1000', '25x200 mm. trykimp. Brædt', 540, 1, 'stk');
INSERT INTO stock VALUES ('1001', '25x125mm. trykimp. Brædt', 360, 1, 'stk');
INSERT INTO stock VALUES ('1001', '25x125mm. trykimp. Brædt', 540, 1, 'stk');
INSERT INTO stock VALUES ('1002', '38x73 mm. Lægte ubh.', 420, 1, 'stk');
INSERT INTO stock VALUES ('1003', '45x95 mm. Reglar ub.', 240, 1, 'stk');
INSERT INTO stock VALUES ('1003', '45x95 mm. Reglar ub.', 270, 1, 'stk');
INSERT INTO stock VALUES ('1003', '45x195 mm. spærtræ ubh.', 480, 1, 'stk');
INSERT INTO stock VALUES ('1003', '45x195 mm. spærtræ ubh.', 600, 1, 'stk');
INSERT INTO stock VALUES ('1004', '97x97 mm. trykimp. Stolpe', 300, 1, 'stk');
INSERT INTO stock VALUES ('1005', '19x100 mm. trykimp. Brædt', 210, 1, 'stk');
INSERT INTO stock VALUES ('1005', '19x100 mm. trykimp. Brædt', 360, 1, 'stk');
INSERT INTO stock VALUES ('1005', '19x100 mm. trykimp. Brædt', 540, 1, 'stk');
INSERT INTO stock VALUES ('1006', 'Plastmo Ecolite blåtonet', 360, 1, 'stk');
INSERT INTO stock VALUES ('1006', 'Plastmo Ecolite blåtonet', 600, 1, 'stk');
INSERT INTO stock VALUES ('1020', 'Plastmo bundskruer 200 stk.', 1, 200, 'pakke');
INSERT INTO stock VALUES ('1021', 'Hulbånd 1x20 mm. 10 mtr.', 1000, 1, 'rulle');
INSERT INTO stock VALUES ('1022', 'Universal 190 mm højre', 190, 1, 'stk');
INSERT INTO stock VALUES ('1023', 'Universal 190 mm venstre', 190, 1, 'stk');
INSERT INTO stock VALUES ('1024', '4,5x60 mm. skruer 200 stk.', 60, 200, 'pakke');
INSERT INTO stock VALUES ('1024', '4,0x50 mm. skruer 250 stk.', 50, 250, 'pakke');
INSERT INTO stock VALUES ('1025', 'Bræddebolt 10x120 mm.', 120, 1, 'stk');
INSERT INTO stock VALUES ('1026', 'Firkantskiver 40x40x11mm', 11, 1, 'stk');
INSERT INTO stock VALUES ('1027', '4,5x70 mm. Skruer 400 stk.', 70, 400, 'pakke');
INSERT INTO stock VALUES ('1027', '4,5x50 mm. Skruer 300 stk.', 50, 300, 'pakke');
INSERT INTO stock VALUES ('1028', 'Stalddørsgreb 50x75', 75, 1, 'sæt');
INSERT INTO stock VALUES ('1029', 'T hængsel 390 mm', 390, 1, 'stk');
INSERT INTO stock VALUES ('1030', 'Vinkelbeslag 35', 35, 1, 'stk');


-- Users
INSERT INTO users VALUES ('Shannon', 'Shannon@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Eve', 'Eve@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Barry', 'Barry@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Felipe', 'Felipe@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Claude', 'Claude@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Trenton', 'Trenton@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('John', 'John@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Vonnie', 'Vonnie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Mignon', 'Mignon@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Jamel', 'Jamel@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Carol', 'Carol@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Delilah', 'Delilah@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Jamal', 'Jamal@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Quiana', 'Quiana@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Becki', 'Becki@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Lai', 'Lai@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Eliza', 'Eliza@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Thea', 'Thea@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Santiago', 'Santiago@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Ramona', 'Ramona@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Geraldo', 'Geraldo@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Colton', 'Colton@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Aaron', 'Aaron@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Lanny', 'Lanny@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Laure', 'Laure@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Noemi', 'Noemi@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Jeffry', 'Jeffry@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Tandy', 'Tandy@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Delena', 'Delena@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Catarina', 'Catarina@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Isaac', 'Isaac@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Freddie', 'Freddie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Todd', 'Todd@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Lucrecia', 'Lucrecia@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Everett', 'Everett@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Johnie', 'Johnie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Tomiko', 'Tomiko@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Dusty', 'Dusty@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Rudolph', 'Rudolph@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Columbus', 'Columbus@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Matthew', 'Matthew@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Damien', 'Damien@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Pete', 'Pete@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Dalila', 'Dalila@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Herman', 'Herman@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Emelina', 'Emelina@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Pat', 'Pat@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Robert', 'Robert@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Travis', 'Travis@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Penni', 'Penni@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Harvey', 'Harvey@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Chadwick', 'Chadwick@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Rochelle', 'Rochelle@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Charlette', 'Charlette@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Shira', 'Shira@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Layne', 'Layne@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Claudio', 'Claudio@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Stevie', 'Stevie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Danna', 'Danna@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Wilbert', 'Wilbert@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Elinor', 'Elinor@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Wiley', 'Wiley@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Sharla', 'Sharla@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Tenesha', 'Tenesha@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Alejandro', 'Alejandro@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Fred', 'Fred@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Qiana', 'Qiana@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Maxwell', 'Maxwell@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Fabian', 'Fabian@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Danial', 'Danial@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Wesley', 'Wesley@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Vance', 'Vance@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Cammy', 'Cammy@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Evelynn', 'Evelynn@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Salome', 'Salome@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Valeria', 'Valeria@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Lucia', 'Lucia@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Aracelis', 'Aracelis@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Lindsy', 'Lindsy@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Joye', 'Joye@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Ailene', 'Ailene@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Ling', 'Ling@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Emmaline', 'Emmaline@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Leland', 'Leland@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Darcy', 'Darcy@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Rocky', 'Rocky@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Winfred', 'Winfred@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Yong', 'Yong@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Lory', 'Lory@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Selina', 'Selina@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Chantel', 'Chantel@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Bertram', 'Bertram@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Tamela', 'Tamela@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Lavada', 'Lavada@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Florentino', 'Florentino@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Johnathon', 'Johnathon@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Shawanda', 'Shawanda@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Jacque', 'Jacque@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Annamarie', 'Annamarie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Charita', 'Charita@somewhere.dk', '1234', 'SALESMAN');
