-- Woods
INSERT INTO stock VALUES ('1000', '25x200 mm. trykimp. Brædt', 360, 1, 'stk');
INSERT INTO stock VALUES ('1001', '25x200 mm. trykimp. Brædt', 540, 1, 'stk');
INSERT INTO stock VALUES ('1002', '25x125mm. trykimp. Brædt', 360, 1, 'stk');
INSERT INTO stock VALUES ('1003', '25x125mm. trykimp. Brædt', 540, 1, 'stk');
INSERT INTO stock VALUES ('1004', '38x73 mm. Lægte ubh.', 420, 1, 'stk');
INSERT INTO stock VALUES ('1005', '45x95 mm. Reglar ub.', 240, 1, 'stk');
INSERT INTO stock VALUES ('1006', '45x95 mm. Reglar ub.', 270, 1, 'stk');
INSERT INTO stock VALUES ('1007', '45x195 mm. spærtræ ubh.', 480, 1, 'stk');
INSERT INTO stock VALUES ('1008', '45x195 mm. spærtræ ubh.', 600, 1, 'stk');
INSERT INTO stock VALUES ('1009', '97x97 mm. trykimp. Stolpe', 300, 1, 'stk');
INSERT INTO stock VALUES ('1010', '19x100 mm. trykimp. Brædt', 210, 1, 'stk');
INSERT INTO stock VALUES ('1011', '19x100 mm. trykimp. Brædt', 360, 1, 'stk');
INSERT INTO stock VALUES ('1012', '19x100 mm. trykimp. Brædt', 540, 1, 'stk');
INSERT INTO stock VALUES ('1013', 'Plastmo Ecolite blåtonet', 360, 1, 'stk');
INSERT INTO stock VALUES ('1014', 'Plastmo Ecolite blåtonet', 600, 1, 'stk');
INSERT INTO stock VALUES ('1030', 'Plastmo bundskruer 200 stk.', 1, 200, 'pakke');
INSERT INTO stock VALUES ('1031', 'Hulbånd 1x20 mm. 10 mtr.', 1000, 1, 'rulle');
INSERT INTO stock VALUES ('1032', 'Universal 190 mm højre', 190, 1, 'stk');
INSERT INTO stock VALUES ('1033', 'Universal 190 mm venstre', 190, 1, 'stk');
INSERT INTO stock VALUES ('1034', '4,5x60 mm. skruer 200 stk.', 60, 200, 'pakke');
INSERT INTO stock VALUES ('1035', '4,0x50 mm. skruer 250 stk.', 50, 250, 'pakke');
INSERT INTO stock VALUES ('1036', 'Bræddebolt 10x120 mm.', 120, 1, 'stk');
INSERT INTO stock VALUES ('1037', 'Firkantskiver 40x40x11mm', 11, 1, 'stk');
INSERT INTO stock VALUES ('1038', '4,5x70 mm. Skruer 400 stk.', 70, 400, 'pakke');
INSERT INTO stock VALUES ('1039', '4,5x50 mm. Skruer 300 stk.', 50, 300, 'pakke');
INSERT INTO stock VALUES ('1040', 'Stalddørsgreb 50x75', 75, 1, 'sæt');
INSERT INTO stock VALUES ('1041', 'T hængsel 390 mm', 390, 1, 'stk');
INSERT INTO stock VALUES ('1042', 'Vinkelbeslag 35', 35, 1, 'stk');


-- Categories
INSERT INTO categories(name) VALUES ('Understernbrædder');
INSERT INTO categories(name) VALUES ('Oversternbrædder');
INSERT INTO categories(name) VALUES ('Lægter');
INSERT INTO categories(name) VALUES ('Reglar');
INSERT INTO categories(name) VALUES ('Spærtræ');
INSERT INTO categories(name) VALUES ('Rem');
INSERT INTO categories(name) VALUES ('Stolpe');
INSERT INTO categories(name) VALUES ('Brædt');
INSERT INTO categories(name) VALUES ('Vandbræt');
INSERT INTO categories(name) VALUES ('Tagplader');
INSERT INTO categories(name) VALUES ('Skruer');
INSERT INTO categories(name) VALUES ('Hulbånd');
INSERT INTO categories(name) VALUES ('Beslag');
INSERT INTO categories(name) VALUES ('Bolt');
INSERT INTO categories(name) VALUES ('Skiver');
INSERT INTO categories(name) VALUES ('Diverse');


-- Categories - Stock link
INSERT INTO stockToCategory VALUES ('1000',1);
INSERT INTO stockToCategory VALUES ('1042',13);
INSERT INTO stockToCategory VALUES ('1041',16);
INSERT INTO stockToCategory VALUES ('1040',16);
INSERT INTO stockToCategory VALUES ('1039',11);
INSERT INTO stockToCategory VALUES ('1038',11);
INSERT INTO stockToCategory VALUES ('1037',15);
INSERT INTO stockToCategory VALUES ('1014',10);
INSERT INTO stockToCategory VALUES ('1036',14);
INSERT INTO stockToCategory VALUES ('1013',10);
INSERT INTO stockToCategory VALUES ('1035',11);
INSERT INTO stockToCategory VALUES ('1012',9);
INSERT INTO stockToCategory VALUES ('1034',11);
INSERT INTO stockToCategory VALUES ('1011',9);
INSERT INTO stockToCategory VALUES ('1033',13);
INSERT INTO stockToCategory VALUES ('1010',9);
INSERT INTO stockToCategory VALUES ('1032',13);
INSERT INTO stockToCategory VALUES ('1031',12);
INSERT INTO stockToCategory VALUES ('1030',11);
INSERT INTO stockToCategory VALUES ('1008',6);
INSERT INTO stockToCategory VALUES ('1007',6);
INSERT INTO stockToCategory VALUES ('1006',4);
INSERT INTO stockToCategory VALUES ('1005',4);
INSERT INTO stockToCategory VALUES ('1004',3);
INSERT INTO stockToCategory VALUES ('1003',2);
INSERT INTO stockToCategory VALUES ('1002',2);
INSERT INTO stockToCategory VALUES ('1001',1);
INSERT INTO stockToCategory VALUES ('1009',7);


-- Users
INSERT INTO users VALUES ('Chong', 'Chong@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Maynard', 'Maynard@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Vincenzo', 'Vincenzo@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Milton', 'Milton@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Damion', 'Damion@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Mary', 'Mary@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Augustine', 'Augustine@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Kenneth', 'Kenneth@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Kareem', 'Kareem@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Ela', 'Ela@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Monty', 'Monty@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Richie', 'Richie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Lucila', 'Lucila@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Bud', 'Bud@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Lacie', 'Lacie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Sam', 'Sam@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Bobby', 'Bobby@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Raymond', 'Raymond@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Breanne', 'Breanne@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Isiah', 'Isiah@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Dion', 'Dion@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Maxwell', 'Maxwell@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Arlen', 'Arlen@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Mitchel', 'Mitchel@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Clora', 'Clora@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Keena', 'Keena@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Hilma', 'Hilma@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Larry', 'Larry@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Darrell', 'Darrell@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Renaldo', 'Renaldo@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Zena', 'Zena@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Justine', 'Justine@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Trista', 'Trista@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Michel', 'Michel@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Lean', 'Lean@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Jene', 'Jene@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Kandy', 'Kandy@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Chad', 'Chad@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Daron', 'Daron@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Neal', 'Neal@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Kit', 'Kit@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Blondell', 'Blondell@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Lauryn', 'Lauryn@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Johnathan', 'Johnathan@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Georgiana', 'Georgiana@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Kristofer', 'Kristofer@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Chi', 'Chi@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Eugenio', 'Eugenio@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Lorette', 'Lorette@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Everett', 'Everett@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Bobbie', 'Bobbie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Edgar', 'Edgar@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Buddy', 'Buddy@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Temple', 'Temple@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Zack', 'Zack@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Shizuko', 'Shizuko@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Hoyt', 'Hoyt@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Jamaal', 'Jamaal@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Annmarie', 'Annmarie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Armand', 'Armand@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Althea', 'Althea@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Angelo', 'Angelo@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Gaston', 'Gaston@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Rob', 'Rob@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Rico', 'Rico@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Flora', 'Flora@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Alejandro', 'Alejandro@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Danille', 'Danille@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Rudolph', 'Rudolph@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Earle', 'Earle@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Herma', 'Herma@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Bradley', 'Bradley@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Emile', 'Emile@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Justin', 'Justin@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Cleotilde', 'Cleotilde@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Tatiana', 'Tatiana@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Britt', 'Britt@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Geraldo', 'Geraldo@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Kami', 'Kami@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Gavin', 'Gavin@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Rodolfo', 'Rodolfo@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Dale', 'Dale@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Dudley', 'Dudley@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Stacie', 'Stacie@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Laree', 'Laree@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Annice', 'Annice@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Oneida', 'Oneida@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Sharonda', 'Sharonda@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Napoleon', 'Napoleon@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Alexia', 'Alexia@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Jayne', 'Jayne@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Sylvester', 'Sylvester@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Krystle', 'Krystle@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Cordell', 'Cordell@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Nancey', 'Nancey@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Alexis', 'Alexis@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Lynelle', 'Lynelle@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Jeannetta', 'Jeannetta@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Malcolm', 'Malcolm@somewhere.dk', '1234', 'SALESMAN');
INSERT INTO users VALUES ('Hollis', 'Hollis@somewhere.dk', '1234', 'SALESMAN');
